name: Update RSS Feed from Notion

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  update-rss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install @notionhq/client dotenv

      - run: node notion-to-rss.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}

      - run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add rss.xml
          git commit -m "Update RSS feed" || echo "No changes"
          git push
